source 'http://rubygems.org'

gem 'rails', '3.1.0.rc1'
gem 'therubyracer'

gem 'sqlite3'

gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'haml-rails'
gem 'jquery-rails'

gem 'aloha_rails', :path => '../../../aloha_rails'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end
